# Options de financement pour La RST
# Remplir uniquement si l’association souhaite recevoir du soutien.

github: []          # Ex: ["teremuhamblin"]
patreon: ""         # Ex: "larst"
open_collective: "" # Ex: "la-rst"
ko_fi: ""           # Ex: "larst"
custom: []          # Ex: ["https://larst.org/dons"]
